### ISSUE TITLE
NSArray The Count Method--pick a word

### ISSUE THREAD

**Issue by amyjoscelyn** [learn-co-curriculum/reading-ios-nsarray#8]
@markedwardmurray 

Near the end, the first paragraph under the new section The Count Method, third sentence:

"The most common use case of this"...

either __use__ or __case__ but not both

**Comment by markedwardmurray** [comment]
was there a problem with the learn editor?

**Comment by markedwardmurray** [comment]
"use case" is a phrase, actually

**Comment by markedwardmurray** [comment]
resolved by 1b23078e6ab522e3a62c185f0355fc4773f47d8f
